dist: xenial

before_cache:
    - sudo mkdir -p /projects/hnd/tools/linux
    - sudo chown -R travis:travis /projects

cache:
    directories:
        - "/projects/hnd/tools/linux"

before_install:
    - sh toolchain_setup.sh

script: make

deploy:
    - provider: releases
      api_key: $GITHUB_OAUTH_TOKEN
      file: "hello"
      skip_cleanup: true
      draft: true
      on:
          tags: false
    - provider: releases
      api_key: $GITHUB_OAUTH_TOKEN
      file: "hello"
      skip_cleanup: true
      on:
          tags: true
