dist: xenial

cache:
    directories:
        - "/opt/hnd/tools/linux"

addons:
    apt:
        packages:
            - libc6:i386
            - libelf1:i386

before_install:
    - sudo ln -s /opt /projects
    - sh toolchain_setup.sh

script: make

deploy:
    - provider: releases
      api_key: $GITHUB_OAUTH_TOKEN
      file: "hello"
      skip_cleanup: true
      draft: true
      on:
          tags: false
    - provider: releases
      api_key: $GITHUB_OAUTH_TOKEN
      file: "hello"
      skip_cleanup: true
      on:
          tags: true
